function(enable_project_optimizations project_name)
    include(CheckIPOSupported)
    check_ipo_supported(RESULT result OUTPUT output)
    if(result)
        set_target_properties(${project_name} PROPERTIES INTERPROCEDURAL_OPTIMIZATION TRUE)
        message(STATUS "IPO / LTO enabled for target ${project_name}")
    else()
        message(WARNING "IPO / LTO not supported: ${output}")
    endif()
endfunction()
